name: SBOM Security Pipeline

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Install Syft
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
    - name: Install Grype
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Generate SBOM for Docker Hub Image with Syft
      run: syft docker:bkimminich/juice-shop -o cyclonedx-json > sbom.json

    - name: Scan SBOM with Grype
      run: grype sbom:sbom.json --fail-on high -o json > grype-sbom-scan.json

    - name: Scan Vulnerable Docker Image (OWASP Juice Shop)
      run: grype bkimminich/juice-shop --fail-on high -o json > grype-image-scan.json

    - name: Upload SBOM as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: SBOM Report
        path: sbom.json

    - name: Upload SBOM Scan Results as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: SBOM Scan Report
        path: grype-sbom-scan.json

    - name: Upload Docker Image Scan Results as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Docker Image Scan Report
        path: grype-image-scan.json
